listening-port=3478
listening-ip=107.191.48.226
relay-ip=107.191.48.226
external-ip=107.191.48.226
realm=mimita.fun
fingerprint
use-auth-secret
static-auth-secret=TEMP_PLACEHOLDER
min-port=49160
max-port=49200
no-loopback-peers
no-multicast-peers
verbose
syslog
cli-password=mimita-cli
