// 09 17 2026
/* purpose
* Registration point for generated Blender clips. Each generated header
* (src/hot-reload/generated/hot-anim-*.h) self-registers its BlenderClip through
* a static initializer when this translation unit loads, so adding a clip is a
* new generated header plus one include here (or an editor-generated file under
* the headerGlob). No kernel enum, no manifest edit per clip.
* Does NOT own animation policy or locomotion; it only publishes clip data.
* Does NOT link into the EXE; only into the replaceable game DLL.
*/
#if defined(MIMITA_GAME_DLL)

#include "hot-reload/hot-animation-blender.h"

// Generated by tools/blender_export_animation.py. Each header registers its clip
// through a static initializer (HotAnimGenerated::k*Registered).
#include "hot-reload/generated/hot-anim-katana-slash.h"

namespace {

// Referenced so the link keeps the registration translation unit alive even if
// a future header defines nothing else.
const bool s_generatedClipsPresent =
    HotAnimGenerated::kanimation_katana_slashRegistered;

} // namespace

#endif // MIMITA_GAME_DLL
